### PR TITLE
Add 0.2.6 to AltStore repo

### PR DESCRIPTION
**Pull request by bazzadazza72**
## Pull Request Description

Add 0.2.6 to the AltStore repository

## Issue Being Fixed

Issue Number: No issue

## Screenshots / Recordings

*No screenshots*

## Checklist

- [x] If a new package was added, did you ensure it works for all supported platforms? Is the package also well maintained?
- [x] Did you add localization for any text? If yes, did you sort the .arb file using ```arb_utils sort <INPUT_FILE>```?
- [x] Check that any changes are related to the issue at hand.

### CODE REVIEW

**Comment by bazzadazza72** [comment]
I should create a GitHub action to do this automatically, let me figure out a way to do that.

**Comment by krinkuto11** [comment]
> I should create a GitHub action to do this automatically, let me figure out a way to do that.

I was taking a look at this issue yesterday a came across [this](https://github.com/osy/altstore-github), maybe it can be of some help.

**Comment by bazzadazza72** [comment]
That's very helpful, I'll have a look at it. Thank you!

**Comment by PartyDonut** [comment]
Thanks for adding 0.2.6 manually
Yes, having it included in the github actions would be good addition.

**Pull request merged**
